### ISSUE TITLE
Development tracker

### ISSUE THREAD

**Issue by Syntasu** [Syntasu/synn-inventory#1]
### A general overview what needs to get done.
Any suggestions what might need to be added are very welcome, you can post them here!

<hr>

- [ ] **Drag and drop**
    - [x] Able to drag and drop in user interface
    - [ ] Server back-end
    - [ ] Interface/library functions
- [ ] **View item details**
    - [x] View item in user interface
- [ ] **Bind item actions**
    - [ ] Show all actions for item in user interface
    - [ ] Replicate actions to the back-end
    - [ ] Interface/library functions
- [ ] **Listen for item actions**
    - [ ]  Server back-end implementation
    - [ ] Client implementation
    - [ ] Interface/library functions
- [ ] **Variable sized inventories**
    - [x] Show variable sized inventories in user interface
    - [ ] Reflect size of inventory on server side
- [ ] **Nested inventory**
    - [ ] Show nested inventory on user interface
    - [ ] Navigation between inventories (back to original inventory)
    - [ ] Server should load nested inventories when opened
 - [ ] **Stack system**
    - [x] Show stack size in user interface
    - [ ] Split stacks in user interface
    - [x] Merge stacks in user interface
 - [ ] **Weight system**
    - [ ] Show total weight in inventory user interface
    - [ ] Server back-end implementation
    - [ ] Listener for when the inventory is overweight
- [ ] **Security**
    - [ ] Perform checksum on data to detect differences
    - [ ] Fully re-sync client inventory if any discrepancies detected
- [ ] **Performance** 
    - [ ] Minimize data and frequency of network calls
    - [ ] Minimize the usage of exports
    - [ ] Don't fall in the the "premature optimization 🕳"
- [ ] **User interface**
    - [ ] Keep fully responsive.
    - [ ] Test various resolutions
    - [ ] Allow for custom themes
    - [ ] Make it easy to make a theme
    - [ ] Allow for custom layouts
    - [ ] Make it easy to define a layout
- [ ] **API (interfaces)**
    - [ ] Provide a C# API (via a DLL which can be referenced)
    - [ ] Provide a Lua API
    - [ ] Provide a JavaScript API
    - [ ] Adapter for custom database (non mysql-async)
- [ ] **Tooling**
    - [ ] Automatically generate resource manifest with a filled out `files` array
    - [ ] Possibly run this each server start if resource manifest is missing
    - [ ] Possibly run a checksum to detect differences
- [ ] **Examples**
    - [ ] Player inventory example
    - [ ] Car trunk inventory example
    - [ ] Shop inventory example
- [ ] **Documentation**
    - [ ] Document the general API
    - [ ] Custom layout docs
    - [ ] Custom theme docs
- [ ] **Error handling, UX improvement**
    - [ ] All (known) errors should have a clear cause and state a resolution for them
    - [ ] Visual feedback in the user inventory when something unexpected happened
    - [ ] Relay "exceptional" situation to server side, to indicate something might be up.
    - [ ] Prefer recovery over blatantly spitting an error out.
    - [ ] Check for integrity of data when assigned.

### After initial release
- [ ] **Tetris-style inventory**
    - [ ] Items with a width and height
    - [ ] AABB bounds checking
    - [ ] Enable/disable tetris-style via API
    - [ ] Gracefully resort back to one-item-per-slot if tetris is disabled
    - [ ] Define item dimensions via API.
- [ ] **Item durability or uses.**
    - [ ] Have a durability bar on items
    - [ ] Remove item when < 0 durability
    - [ ] Define durability via API
